[package]
name = "qrforth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
strip = true
lto = true

[dependencies]
wasm-bindgen = "0.2.88"