[package]
name = "qrforth"
version = "0.1.0"
edition = "2021"
authors = ["Matt Deeds"]
homepage = "https://qrforth.com/"

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = true
# strip = "debuginfo"
lto = true